// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projektAspNet.Models;

#nullable disable

namespace projektAspNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projektAspNet.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "MSI",
                            FirstName = "Robert",
                            LastName = "Kowalski",
                            NIP = "1111111111",
                            Pesel = "11111111111"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Acer",
                            FirstName = "Marcin",
                            LastName = "Zając",
                            NIP = "2222222222",
                            Pesel = "22222222222"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Intel",
                            FirstName = "Fabian",
                            LastName = "Nowak",
                            NIP = "3333333333",
                            Pesel = "33333333333"
                        });
                });

            modelBuilder.Entity("projektAspNet.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("KayakType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfKayaks")
                        .HasColumnType("int");

                    b.Property<int>("RouteID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.HasIndex("RouteID");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerID = 1,
                            KayakType = "pojedynczy",
                            NumberOfKayaks = 3,
                            RouteID = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerID = 2,
                            KayakType = "podwójny",
                            NumberOfKayaks = 4,
                            RouteID = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerID = 3,
                            KayakType = "pojedynczy",
                            NumberOfKayaks = 2,
                            RouteID = 3
                        });
                });

            modelBuilder.Entity("projektAspNet.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RouteName = "wadowice-witanowice"
                        },
                        new
                        {
                            Id = 2,
                            RouteName = "wadowice-woźniki"
                        },
                        new
                        {
                            Id = 3,
                            RouteName = "wadowice-grodzisko"
                        },
                        new
                        {
                            Id = 4,
                            RouteName = "witanowice-woźniki"
                        },
                        new
                        {
                            Id = 5,
                            RouteName = "witanowice-grodzisko"
                        },
                        new
                        {
                            Id = 6,
                            RouteName = "woźniki-grodzisko"
                        });
                });

            modelBuilder.Entity("projektAspNet.Models.Customer", b =>
                {
                    b.HasOne("projektAspNet.Models.Reservation", null)
                        .WithMany("Customers")
                        .HasForeignKey("ReservationId");
                });

            modelBuilder.Entity("projektAspNet.Models.Reservation", b =>
                {
                    b.HasOne("projektAspNet.Models.Customer", "Customer")
                        .WithMany("Reservation")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projektAspNet.Models.Route", "Route")
                        .WithMany("Reservation")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("projektAspNet.Models.Route", b =>
                {
                    b.HasOne("projektAspNet.Models.Reservation", null)
                        .WithMany("Routes")
                        .HasForeignKey("ReservationId");
                });

            modelBuilder.Entity("projektAspNet.Models.Customer", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("projektAspNet.Models.Reservation", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("projektAspNet.Models.Route", b =>
                {
                    b.Navigation("Reservation");
                });
#pragma warning restore 612, 618
        }
    }
}
